# Generated by Django 2.1.1 on 2018-11-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20181128_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='palm_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='plastic_free',
            field=models.BooleanField(default=False),
        ),
    ]
