# Generated by Django 2.1.1 on 2018-11-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20181128_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Bars', 'Bars'), ('Shaving', 'Shaving'), ('Oil', 'Oil'), ('Shampoo', 'Shampoo'), ('Salts', 'Salts'), ('Cream', 'Cream'), ('Liquid soap', 'Liquid soap')], default='', max_length=150),
        ),
    ]
