# Generated by Django 2.1.1 on 2018-12-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20181129_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='Country',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='Province',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='apartment',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='city',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='street_address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Bars', 'Bars'), ('Shaving', 'Shaving'), ('Oil', 'Oil'), ('Shampoo', 'Shampoo'), ('Salts', 'Salts'), ('Cream', 'Cream'), ('Liquid soap', 'Liquid soap'), ('Clear soap', 'Clear soap'), ('Cologne & Perfume', 'Cologne & Perfume'), ('Lotion', 'Lotion')], default='', max_length=150),
        ),
    ]
