# Generated by Django 2.1.1 on 2018-12-06 07:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20181203_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
