# Generated by Django 2.1.1 on 2018-12-06 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
